### ISSUE TITLE
[Enhancement] showDialog in avalonia ui is async,could add a method named showDialogAsync with async tag in dialogService

### ISSUE THREAD

**Issue by yaobiao131** [AvaloniaCommunity/Prism.Avalonia#106]
## Description
ShowDialog in avalonia ui is asynchronous. Should a method named showDialogAsync with an asynchronous tag be added to the dialogService to be compatible with wpf's showdialog?

## Context
Add any other context, examples, or screenshots about the feature request here.

**Comment by Coolkeke** [comment]
It is not recommended to do this as it can cause confusion for developers

**Comment by DamianSuess** [comment]
@yaobiao131, thank you for the suggestion. I would however bring this up up on the main Prism repo thread.

Currently, with the Prism 9.0.x upgrades the `IDialogService` interface has moved into the framework's Prism.Core for a standardization across the platforms. Check out #129  _Prism v9.0.271-pre upgrade_

Since I can't transfer this issue, please open it up over there.
